# Generated by Django 6.0.4 on 2026-04-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='used_trial_upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
